# Generated by Django 5.1.7 on 2025-03-18 15:58

import myapp.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.IntegerField(choices=[(1, 'HIGH'), (2, 'MEDIUM'), (3, 'LOW')], default=myapp.constants.AppointmentType['LOW']),
        ),
    ]
