# Generated by Django 5.1.7 on 2025-03-19 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.doctor'),
        ),
    ]
