# Generated by Django 5.1.7 on 2025-03-19 08:23

import django.db.models.deletion
import myapp.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_patient_appointments_alter_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.IntegerField(choices=[(1, 'LOW'), (2, 'MEDIUM'), (3, 'HIGH')], default=myapp.constants.AppointmentType['LOW']),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_dr_id', to='myapp.doctor', verbose_name='Head Doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department', verbose_name='Department Id'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='myapp.doctor'),
        ),
    ]
