# Generated by Django 5.1.7 on 2025-03-21 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_prescription_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_doctor', to='myapp.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_patient', to='myapp.patient', verbose_name='Patient'),
        ),
    ]
