# Generated by Django 5.1.7 on 2025-03-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_surgery_doctor_alter_surgery_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(blank=True, related_name='doctor_patients', to='myapp.doctor'),
        ),
    ]
