# Generated by Django 5.1.7 on 2025-03-21 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appoint_patient', to='myapp.appointment'),
        ),
    ]
