# Generated by Django 5.1.7 on 2025-03-21 11:44

import myapp.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_patient_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'SCHEDULED'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('missed', 'MISSED')], default=myapp.constants.AppointmentStatus['SCHEDULED'], max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.IntegerField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], default=myapp.constants.AppointmentType['LOW']),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='type',
            field=models.CharField(choices=[('primary care', 'PRIMARY_CARE'), ('consultant', 'CONSULTANT'), ('specialist', 'SPECIALIST')], default=myapp.constants.DoctorType['PRIMARY_CARE'], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default=myapp.constants.GenderType['MALE'], max_length=100),
        ),
    ]
