# Generated by Django 5.1.7 on 2025-03-21 11:51

import myapp.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_appointment_status_alter_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], default=myapp.constants.AppointmentType['LOW'], max_length=100),
        ),
    ]
