# Generated by Django 5.1.7 on 2025-03-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pres_app_id', to='myapp.appointment', verbose_name='Appointment Name'),
        ),
    ]
